### ISSUE TITLE
Missing input validation

### ISSUE THREAD

**Issue by fscheel** [nmdp-bioinformatics/service-haplotype-frequency-curation#15]
The current state of the service is a prototype. As such almost no input validation, cross checks and sanity checks are performed. They need to be implemented.

**Comment by mmaiers-nmdp** [comment]
For example this resolution field 
```json
"ResolutionData": [
    {
      "scopeElement": null,
      "resolution": "4-Field"
    }
]
```
should be validated against the enum from the yaml

```yaml
 ResolutionInfo:
    title: ResolutionInfo
    properties:
      scopeElement:
        type: string
      resolution:
        type: string
        description: resolution of the data
        enum:
          - G
          - P
          - gNMDP
          - gDKMS
          - 2-Field
          - 4-Field
          - 6-Field
          - 8-Field
          - Serology
````
